### ISSUE TITLE
question about relation score

### ISSUE THREAD

**Issue by Leo-Repo** [MANLP-suda/JML#9]
https://github.com/MANLP-suda/JML/blob/ad277d9087340a66d1bade1c5b0c4d276fd4cbbd/JML_opened/bert/sentiment_modeling.py#L214
Hi, author,
relation score 是一个0-1小数，乘以ResNet提取的图片特征，为什么可以说控制图片信息的输入呢？我能理解当relation score为0时图片信息为0，但是当不为0时，图片的特征整体乘以这样的一个小数，有什么意义呢？
您费心了！

**Comment by MANLP-suda** [comment]
小数是图片的相关性系数。如果相关性很弱的话，就减少图片信息的输入。 你可以看下数据集来源的引用文章，他也是这么弄的

**Comment by Leo-Repo** [comment]
谢谢解答:)
